### ISSUE TITLE
Generates site, but has issues with submodules

### ISSUE THREAD

**Issue by jtsternberg** [WebDevStudios/generator-wd-s#6]
Hard to explain, but goes like this... Generate site, then `git init` then `git add .`. You'll see the errors in your console, but basically it doesn't like the submodule structure. the only we could fix was to `rm -rf submodule/path` on every submodule, then redo `git submodule add submodule.url submodule/path` with each one. It's not super difficult, but something we'd like to fix.

**Comment by CamdenSegal** [comment]
Ok I've got some ideas on why that would be, that error points me to think that submodules are being handle weirdly in the generator (they are downloaded, then copied and run through the same text replace as everything else).

The root git folder is not copied over though meaning that the submodule bindings break.

So how do we preserve the submodules while also not including the git history of wd_s in the project? Should we just leave the wd_s .git folder in place and count on users to change the origin etc?

**Comment by jtsternberg** [comment]
Yes, I think leaving the .git folder is ok, since devs will almost always be handling this task. Would be good to add to the readme though.

**Comment by bradp** [comment]
Can we run git commands at the end? So we could remove the origin there, or clear out the history.

**Comment by CamdenSegal** [comment]
yeah I could spawn a git command at the end

**Comment by CamdenSegal** [comment]
Should we clear history or just remove origin?

**Comment by jtsternberg** [comment]
clear history would be ideal.

**Comment by bradp** [comment]
Ideally both, right?

**Comment by jtsternberg** [comment]
Ha, sorry, that's what I meant. for sure origin, ideally history.

**Comment by CamdenSegal** [comment]
Should be fixed by the 1.0.0 rewrite
